### ISSUE TITLE
get_delayed_value is returning NaN

### ISSUE THREAD

**Issue by rustyconover** [microprediction/microprediction#25]
This seems to have changed, my integration tests caught this.

JSON doesn't allow NaNs.

```
$ curl http://api.microprediction.org/live/delayed::70::South_Australia_Electricity_Price.json
NaN

$ curl http://api.microprediction.org/live/delayed::310::South_Australia_Electricity_Price.json
NaN

$ curl http://api.microprediction.org/live/delayed::910::South_Australia_Electricity_Price.json
NaN
```

**Comment by microprediction** [comment]
Hmmm. 
 
http://api.microprediction.org/lagged/South_Australia_Electricity_Price.json
is working but it has been 14 hours since a value was published

**Comment by rustyconover** [comment]
I'd suggest that the API just returns the last value and not a NaN.

I've started switching over to get_lagged.  Maybe we should remove get_lagged_values and get_lagged_times.  Having those functions in the API may lead to problems we've previously discussed.

Rusty

**Comment by microprediction** [comment]
Agree. 
 
Python client now has a.  get_lagged_values_and_times()  that makes one call only

**Comment by microprediction** [comment]
Likely caused by a TTL on the value. Garbage truck can be a bit aggressive

**Comment by microprediction** [comment]
How should we return a null?

**Comment by microprediction** [comment]
What's happening is that the stream isn't being published so the delayed value dies after TTL expires.

**Comment by microprediction** [comment]
Probably get_delayed shouldn't be used.
