### ISSUE TITLE
from microprediction import MicroPoll, create_key doesn't work

### ISSUE THREAD

**Issue by cuckookernel** [microprediction/microprediction#33]
This is found in one of the READMEs at the root of the repo. 
For importing `MicroPoll` what seems to work is `from microprediction.polling import MicroPoll`

For create_key it is not clear. I found `create_key` methods in `old_conventions.py`  but not a standalone function.
Maybe one needs something from the separate `muid` module (?)

**Comment by microprediction** [comment]
Thanks! I will add MicroPoll to __init__
Also I I’ll add create_key for backward compat 
I usually say new_key which is a synonym 


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by microprediction** [comment]
Fixed in 0.15.11
