### ISSUE TITLE
Monotonic NN

### ISSUE THREAD

**Issue by microprediction** [microprediction/microprediction#36]
https://arxiv.org/pdf/1908.05164.pdf

**Comment by rustyconover** [comment]
I've given the paper a read and run their Python code.  It seems this
network is super useful when there is a direct relationship from a
regressor to the output, while that may seem useful for quantile
regression, it would be difficult to use in practice.

Typically, we are going to perform regression on multiple quantiles at the
same time, using this code would require the network to be run for each
quantile.

Rusty
