### ISSUE TITLE
MicroCrawler and MicroWriter __repr__s need to return string, not dict

### ISSUE THREAD

**Issue by timkpaine** [microprediction/microprediction#39]
https://github.com/microprediction/microprediction/blob/63226fdb4d2462df923b0561639316010cbfe9a3/microprediction/crawler.py#L336

https://github.com/microprediction/microprediction/blob/3ff44c74cd4fde710a0ffbefbcc63586844c16f7/microprediction/writer.py#L20

**Comment by microprediction** [comment]
Fixed now.
