### ISSUE TITLE
Missing time series forecasting package

### ISSUE THREAD

**Issue by jdb78** [microprediction/microprediction#41]
In your [blog](https://www-microprediction-com.cdn.ampproject.org/c/s/www.microprediction.com/blog/popular-timeseries-packages?hs_amp=true), you forgot to include [pytorch-forecasting](https://pytorch-forecasting.readthedocs.io/) which is a new package with already 3372 downloads last month.

I lack permission to add cards to your project as you suggested in the blog.

**Comment by rustyconover** [comment]
@jdb78 Thanks!  That's a pretty cool package actually.  I'm sure @microprediction will add it.

**Comment by microprediction** [comment]
Hi Jan  (@jdb78),
   
    Thanks for that. I see you've done a nice job with this library. I'm adding to the list but also about 80% of the way through a hello world notebook example. If you wouldn't mind taking a look and advising on the best way to apply the trained model out of sample, I'd appreciate it. I'm not sure if I need to create a new dataset inside a loop or if there is a better way.   
   
   Notebook is at : https://github.com/microprediction/timeseries-notebooks/blob/main/pytorch_forecasting_hello.ipynb

Peter

**Comment by rustyconover** [comment]
Peter wouldn't that just be calling forward() on the model?

**Comment by microprediction** [comment]
This belongs in timemachines issues.
