### ISSUE TITLE
neuralprophet 119

### ISSUE THREAD

**Issue by microprediction** [microprediction/microprediction#44]

**Comment by microprediction** [comment]
Aaron is going to write  a skater.

**Comment by free-soellingeraj** [comment]
Starting. 
Ran the test notebook for fbprophet successfully with no changes.

**Comment by free-soellingeraj** [comment]
I think this may be closed now because you already did it.

**Comment by free-soellingeraj** [comment]
What evaluators will work for nproph implementation?

**Comment by free-soellingeraj** [comment]
What criteria is appropriate for nproph defaults? 
e.g. `PMD_CRITERIA = ['aic', 'aicc', 'bic', 'hqic']`

**Comment by free-soellingeraj** [comment]
I opened a PR into the main timemachines repo
It's not ready to merge yet
https://github.com/microprediction/timemachines/pull/9

**Comment by microprediction** [comment]
Discuss Tue 8pm?

Peter Cotton, PhD
Senior Vice President, Chief Data Scientist
D 609-497-0443 M 646-637-1338
intechinvestments.com<https://www.intechinvestments.com/>
[signature_14790797]<http://>
[signature_1097494014]<http://>

This message, including its attachments, contains information from Intech Investment Management LLC or one of its affiliates, which may be confidential and/or privileged. If it has been sent to you in error, please reply to advise the sender of the error and immediately delete this message. Thank you.
l

**Comment by microprediction** [comment]
Fbprophet or neural?


________________________________

This electronic message, including its attachments, contains information from Janus Henderson Investors. Janus Henderson Investors is the name under which various entities, including Janus Capital Management LLC, Perkins Investment Management LLC and Intech Investment Management LLC provide investment products and services. All of these companies are wholly owned subsidiaries of Janus Henderson Group plc (incorporated in Jersey, registered no.101484, registered office 13 Castle Street, St Helier, Jersey JE1 1ES). This email contains information which is confidential and may be privileged and attorney work product, intended solely for the use of the individual or entity named above. Your personal information will be kept in accordance with the applicable data privacy laws and Janus Henderson's Privacy Policy. A copy of the document is available under the Privacy Policy section of our website at www.janushenderson.com and in hard copy by sending a request to privacy@janushenderson.com If you are not the intended recipient, be aware that you must not read this email and that any disclosure, copying,distribution or use of the contents of this email is prohibited. If you have received this email in error, please immediately notify the sender and delete the original emal and its attachments without reading or saving in any manner.

**Comment by free-soellingeraj** [comment]
Neural.  I got confused right in the beginning

**Comment by free-soellingeraj** [comment]
8 pm ok
