### ISSUE TITLE
Mac install fails

### ISSUE THREAD

**Issue by mirono** [microprediction/microprediction#57]
(qqq)  ~/Dev/AnacondaProjects/microprediction/ [microprediction] pip install microprediction        
Collecting microprediction
  Using cached microprediction-0.19.5-py3-none-any.whl (71 kB)
Collecting microconventions>=0.5.0
  Using cached microconventions-0.5.4-py3-none-any.whl (16 kB)
Collecting apscheduler
  Using cached APScheduler-3.9.1-py2.py3-none-any.whl (59 kB)
Collecting tdigest
  Using cached tdigest-0.5.2.2-py3-none-any.whl (9.4 kB)
Collecting copulas
  Using cached copulas-0.3.0-py2.py3-none-any.whl (44 kB)
Collecting genson
  Using cached genson-1.2.2.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Collecting hyperopt
  Using cached hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
Collecting pytz>=2021.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting contexttimer
  Using cached contexttimer-0.3.3.tar.gz (4.9 kB)
  Preparing metadata (setup.py) ... done
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting pycoingecko
  Using cached pycoingecko-2.2.0-py3-none-any.whl (8.3 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.0.2-cp310-cp310-macosx_10_13_x86_64.whl (8.0 MB)
Collecting pandas
  Using cached pandas-1.4.1-cp310-cp310-macosx_10_9_x86_64.whl (11.5 MB)
Collecting numpy>=1.20.1
  Using cached numpy-1.22.3-cp310-cp310-macosx_10_14_x86_64.whl (17.6 MB)
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by microprediction** [comment]
Thanks taking a look

**Comment by microprediction** [comment]
You're on macos? Which Python ver?

**Comment by microprediction** [comment]
Also are you on mac silicon (newish M1?)

**Comment by microprediction** [comment]
Do me a favor and try now (0.20.0). But before you do

       pip install --upgrade pip

**Comment by mirono** [comment]
 ~/Dev/AnacondaProjects/microprediction/ [microprediction] pip install --upgrade pip 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (22.0.3)
Collecting pip
  Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.3
    Uninstalling pip-22.0.3:
      Successfully uninstalled pip-22.0.3
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed pip-22.0.4

**Comment by mirono** [comment]
This is intel Mac python 3.10.1

**Comment by mirono** [comment]
After pip upgrade it installed ok
